# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list

  build-grpc:
    desc: Build GRPC files
    deps: [clean]
    cmds:
    - cmd: mkdir protobuf
      ignore_error: true
      silent: true
    - protoc --go_out=protobuf/ --go-grpc_out=protobuf/ --proto_path=api/grpc-spec reservation-service_v1.proto

  clean:
    desc: Clean project
    cmds:
      - cmd: rm -rd protobuf
        ignore_error: true
        silent: true